#!/usr/bin/python3

import time

import sys
import pdb
import feedmejack as fmj
from feedmejack.utility import *

if __name__ == '__main__':
    defaults = {}
    defaults.update(fmj.settings.default_tool_settings())
    defaults.update(fmj.settings.default_position_settings(label='start',
                                                         x=10, y=10, z=50))
    defaults.update(fmj.settings.default_position_settings(label='end',
                                                         x=290, y=290, z=50))
    defaults.update(fmj.settings.default_comms_settings())

    settings = fmj.settings.Settings(d=defaults)
    settings = fmj.settings.parse_tool_settings(settings=settings)
    settings = fmj.settings.parse_position_settings(label='start',
                                                  settings=settings)
    settings = fmj.settings.parse_position_settings(label='end',
                                                  settings=settings)
    settings = fmj.settings.parse_comms_settings(settings=settings)

    others = {"home": True,
              "park": True,
              "debug": False,
              "dryrun": False,
              "step": clean(0.1, "10000.000"),
              "raise_z": True,
              }
    settings = fmj.settings.parse_settings(defaults=others, settings=settings)
    settings = fmj.settings.finalize(settings=settings)

    if len(sys.argv) > 1:
        print("what's up with this command line: %s" % (sys.argv,))
        sys.exit(1)

    tool = settings.tool
    print("tool: %s tool.z: %s" % (tool,tool.z))

    mill = fmj.Mill(settings=settings)
    if not settings.dryrun:
        mill.reset()
        mill.setup()

    cmds = []
    if settings.feed > 0:
        code = mill.gcode.G1
        args = {'f':settings.feed}
        cmds.append(mill.gcode.F(f=settings.feed))
    else:
        code = mill.gcode.G0
        args = {}

    cmds += [
        mill.gcode.G0(end={'z':50}),
        mill.gcode.G0(end={'x':settings.start_x,'y':settings.start_y}),
        mill.gcode.G0(end={'z':settings.start_z * Decimal(1.1, "10000.000")}),
        code(end={'z':settings.start_z})
        ]
    for z1, z0 in sweep(settings.start_z, settings.end_z, -abs(settings.step),
                        quant="100.00"):
        cmds += [
            code(end={'z':z1}),
            code(end={'x':settings.end_x, 'y':settings.end_y, 'z':z0}),
            code(end={'x':settings.start_x, 'y':settings.start_y, 'z':z0}),
        ]

    for cmd in cmds:
        print("%s" % (cmd,))
        if not settings.dryrun:
            mill.send(cmd)
            mill.wait_for_idle()

    if settings.park and not settings.dryrun:
        mill.park()
    mill.end()
