#!/usr/bin/python3

import time

import sys
import pdb
import feedmejack as fmj
from feedmejack.utility import *
from decimal import Decimal

if __name__ == '__main__':
    defaults = {}
    defaults.update(fmj.policy.default_tool_settings())
    defaults.update(fmj.policy.default_position_settings(label='start',
                                                         x=10, y=10, z=50))
    defaults.update(fmj.policy.default_position_settings(label='end',
                                                         x=290, y=290, z=50))
    defaults.update(fmj.policy.default_comms_settings())

    settings = fmj.policy.Settings(d=defaults)
    settings = fmj.policy.parse_tool_settings(settings=settings)
    settings = fmj.policy.parse_position_settings(label='start',
                                                  settings=settings)
    settings = fmj.policy.parse_position_settings(label='end',
                                                  settings=settings)
    settings = fmj.policy.parse_comms_settings(settings=settings)

    others = {"home": True,
              "park": True,
              "debug": False,
              "dryrun": False,
              "step": clean(0.1),
              }
    settings = fmj.policy.parse_settings(defaults=others, settings=settings)
    settings = fmj.policy.finalize(settings=settings)

    if len(sys.argv) > 1:
        print("what's up with this command line: %s" % (sys.argv,))
        sys.exit(1)

    tool = settings.tool
    print("tool: %s tool.z: %s" % (tool,tool.z))

    if not settings.dryrun:
        mill = fmj.Mill(settings=settings)

        mill.reset()
        mill.setup()

    if settings.feed > 0:
        code = fmj.gcode.G1
        args = {'f':settings.feed}
    else:
        code = fmj.gcode.G0
        args = {}

    cmds = [
        fmj.gcode.G0(end={'z':50}),
        fmj.gcode.G0(end={'x':settings.start_x,'y':settings.start_y}),
        fmj.gcode.G0(end={'z':settings.start_z * Decimal(1.1)}),
        code(end={'z':settings.start_z}, **args),
        code(end={'x':settings.end_x, 'y':settings.end_y, 'z':settings.end_z},
             **args)
        ]

    for cmd in cmds:
        print("%s" % (cmd,))
        if not settings.dryrun:
            mill.send(cmd)
            mill.wait_for_idle()

    if settings.park and not settings.dryrun:
        mill.park()
